# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir httpx asyncio python-dotenv tapo pandas

# Run app.py when the container launches
CMD ["python", "./waching_dryer_alert.py"]
