import httpx
import asyncio
import os
from datetime import datetime, timedelta
from tapo import ApiClient, EnergyDataInterval
from dotenv import load_dotenv

df_energy_consumption.set_index('Date', inplace=True)
solar_energy_generated_today = df_energy_consumption.loc[str(datetime.today().date())]['Value']
max_solar_energy = df_energy_consumption['Value'].max()
print(f"The energy consumed today has been {solar_energy_generated_today / 1000:.4g} kWh which is {solar_energy_generated_today / max_solar_energy:.1%} of the maximum energy generated this year.")
# print(f"The energy generated by the solar today has been {dict_energy_data_daily['data'][-1]} kWh")